TIKPAN_ROOT = "👑 Tikpan 官方独家节点"

CATEGORY_IMAGE = f"{TIKPAN_ROOT}/01 图片 Image"
CATEGORY_VIDEO = f"{TIKPAN_ROOT}/02 视频 Video"
CATEGORY_AUDIO = f"{TIKPAN_ROOT}/03 音频 Audio"
CATEGORY_TEXT_MULTIMODAL = f"{TIKPAN_ROOT}/04 文字与多模态 Text & Multimodal"
CATEGORY_PROMPT_ANALYSIS = f"{TIKPAN_ROOT}/05 提示词与分析 Prompt & Analysis"
CATEGORY_TOOLS = f"{TIKPAN_ROOT}/06 任务与并发 Tools"
CATEGORY_BENEFIT = f"{TIKPAN_ROOT}/07 福利 Benefit"
CATEGORY_NEW_IP233 = f"{TIKPAN_ROOT}/08 new.ip233.com 中转站"
CATEGORY_CANGYUAN = CATEGORY_NEW_IP233

CATEGORY_ASYNC_ENGINE = f"{CATEGORY_TOOLS}/异步任务池 Async Engine"
CATEGORY_PARALLEL_ENGINE = f"{CATEGORY_TOOLS}/并发引擎 Parallel Engine"
CATEGORY_PROMPT_LIBRARY = f"{CATEGORY_PROMPT_ANALYSIS}/提示词库 Prompt Library"
CATEGORY_PSD_TOOLS = f"{CATEGORY_TOOLS}/PSD Tools"
